### ISSUE TITLE
ASTechTalk の Closing 

### ISSUE THREAD

**Issue by koudaiii** [ASTechTalk/1-my-paas-by-docker#1]
https://github.com/blog/2164-introducing-unlimited-private-repositories

@ASTechTalk/owners 
@asktkhr 
@ksoichiro 
@hoku 
@neogym 
@YAMADA-Yusuke 

よりASTechTalk が User 単位で課金対象になります。

自身で発表されてるものを自分の repository に移す。または repository を delete しましょう。

忘れないうちにこのグループを消そうと思いますー 😄

**Comment by ksoichiro** [comment]
@koudaiii これって、publicなリポジトリは引き続きfreeではないんですかね？
きちんと読んでないですが…

**Comment by koudaiii** [comment]
Personal はそのまま無料公開で行けそうなんですけど、この組織系がダメっぽいです。
これ作ったタイミングはまだちゃんと organization の機能が出来る前なのでいつかのタイミングって感じです…一旦待つのもありかもしれないです！！

**Comment by ksoichiro** [comment]
なるほど・・
https://github.com/pricing に

> GitHub is free to use for public and open source projects. 

と大きく書いてあるのでセーフなのかなと思ってしまいましたが・・
ちょっと様子を見てもいいのかもしれないですね。

**Comment by asktkhr** [comment]
これ、organizationでもprivate repositry作らなければ
'Unlimited members and public repositories for free.'
のままじゃないですか？

今ってお金払ってないですよね？

**Comment by koudaiii** [comment]
Billing overview

```

Unlimited public repositories for free

Upgrade Introducing unlimited private repositories for teams
```

他の organization でアップグレードのメールが来たので、ついでに、この organization の setting を見に行ったらバッチリ書いてありました :bow: 

お騒がせしました ><

**Comment by asktkhr** [comment]
まぁすぐにってわけでもないし自動で変える時は12カ月前には言うよって感じみたいですね。

ちなみにウチプラン変えられると$300以上月額コスト増える、、

**Comment by koudaiii** [comment]
https://github.com/blog/2173-more-contributions-on-your-profile

Longest Streak...

**Comment by asktkhr** [comment]
お金かかってないにしろ、もうとじますかw

**Comment by koudaiii** [comment]
たしかに！

**Comment by asktkhr** [comment]
あ、issueのcloseじゃなくてこのorganizationをって意味でしたw
